apiVersion: v1
kind: Service
metadata:
    name: sample-python-svc
spec:
  selector:
    app.kubernetes.io/name: python-test
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 30275
  type: NodePort
